title: Powers Hell
description: Great Power Is Great Fun
permalink: /:year/:month/:day/:title/
twitter_username: powers_hell
github_username: tabs-not-spaces

date_format: "%-d %b"
excerpt_separator: <!--more-->
markdown: kramdown
theme: minima

include:
  - node_modules

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
