title: Powers Hell
description: Great power is great fun
permalink: /:year/:month/:day/:title/
twitter_username: powers_hell
github_username: tabs-not-spaces

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 5
paginate_path: "/page:num/"

date_format: "%-d %b"
excerpt_separator: <!--more-->
markdown: kramdown
theme: minima

include:
  - node_modules

exclude:
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
